### ISSUE TITLE
Charger Upgrade Not Working

### ISSUE THREAD

**Issue by LordViathan** [EngineersMods/EngineersWorkshop#10]
###### **Forge Version & Engineer's Workshop Version**
> Forge: 12.18.3.2185
> Mod Version: 1.0.6

###### **Expected behavior**
> The Charger Upgrade item would be able to be installed in the workbench.

###### **Actual Behavior**
> The Charger Upgrade can not be installed, as a global upgrade, crafting table upgrade, or furnace upgrade.

**Comment by EwyBoy** [comment]
The Charger upgrade is redundant. It serves 0 uses and will be removed in a future update.

**Comment by nrllewellyn** [comment]
I'm confused--is this functionality being taken over by some other item? Currently it allows you to instantly smelt things, if it has been given enough time to charge. It's actually quite useful.

**Comment by EwyBoy** [comment]
Sorry for missinformation. It was tempearly disabled cause of some issues. Gonna try make it useable later this week.

**Comment by nrllewellyn** [comment]
Gotcha. Thanks! :-)

**Comment by JorVaCoding** [comment]
Fixed 😄
