### ISSUE TITLE
[Obligatory Suggestion] Pulverizer

### ISSUE THREAD

**Issue by KidsDontPlay** [EngineersMods/EngineersWorkshop#13]
It would be cool to have a crusher upgrade.
You can use different grinders from mods as upgrade.
If the idea is acceptable for you I could make a pull request.

**Comment by JorVaCoding** [comment]
New machines are on the list of things that we want... really want.
We still need to figure out a system of making them and how we want them to be implemented...
But I can promise you that it will be sometime in the near future.
Chests, grinder, and alloy smelters(Possibly) are the main things I'm looking at to add.

**Comment by JorVaCoding** [comment]
Added in version 1.2.0 (On curseforge)
