### ISSUE TITLE
Not drawing RF directly from rf tiles

### ISSUE THREAD

**Issue by scollenburg** [EngineersMods/EngineersWorkshop#16]
###### **Forge Version & Engineer's Workshop Version**
Forge 12.18.3.2202; EW 1.1.2 (for minecraft 1.10.2); 

###### **Expected behavior**
RF should be pulled directly from the Capacitor Bank (tile) immediately once the RF upgrade is applied.

###### **Actual Behavior**
Placed new Workshop table next to a EnderIO [Creative] Capacitor Bank. Added RF upgrade to table. No RF was pulled.

Once I placed energy conduit, the Table started accepting RF. I was able to remove the conduit & the table continued to accept RF.

###### **Link to Crashlog or Forgelog** *[If Applicable]*
n/a

###### **Steps to reproduce** *[If Applicable]*
See Actual Behavoir

**Comment by MatthiasMann** [comment]
This is probably a missing neighbor change notification when adding/removing the RF upgrade so that EnderIO can update it's cache of RF capable neighbors.

**Comment by JorVaCoding** [comment]
Fixed, just needed to notify neighbor blocks of a change.

**Comment by scollenburg** [comment]
Awesome, thanks!
