### ISSUE TITLE
[1.10.2] onCrafted() NullPointerException Server Console Spam

### ISSUE THREAD

**Issue by rmnaderdev** [EngineersMods/EngineersWorkshop#19]
###### **Forge Version & Engineer's Workshop Version**
> forge 1.10.2 - 12.18.3.2221 & SW version 1.1.4

###### **Expected behavior**
> Not to spam console.

###### **Actual Behavior**
> Console is spamming onCrafted() NullPointerExceptions when there's a Workshop table running in a loaded chunk. When we turn the Workshop Table off using red stone, the errors stopped. Note: Sponge is not the issue, I removed Sponge from the server and the errors still spam.

###### **Link to Crashlog or Forgelog** *[If Applicable]*
> Here's the snippet from the fml logs: http://pastebin.com/n6TPSjTc

###### **Steps to reproduce** *[If Applicable]*
>

**Comment by EwyBoy** [comment]
@JorVaCoding haven't we fixed that issue like 3 times now?

**Comment by EwyBoy** [comment]
This bug should be fixed now in build 1.1.5. The build should be up on Curse in about 15 min from when I posted this.

**Comment by rmnaderdev** [comment]
Awesome thanks!
