### ISSUE TITLE
Clear button not working

### ISSUE THREAD

**Issue by EwyBoy** [EngineersMods/EngineersWorkshop#23]
👍

**Comment by JorVaCoding** [comment]
All the code for shift clicking and clearing stuff (moving stuff to and from player inventory) has been commented out and needs to be re-added/ updated to 1.10 code

**Comment by kitsu** [comment]
This does indeed work in the latest update. I wish it tried clearing items to the nearest storage upgrade slot before the player's inventory though.

**Comment by EwyBoy** [comment]
We can add another clear button, one for player inv and one for internal inv

**Comment by JorVaCoding** [comment]
#32
