### ISSUE TITLE
Compatibility with Woot

### ISSUE THREAD

**Issue by quixQuery** [EngineersMods/EngineersWorkshop#24]
###### **Forge Version & Engineer's Workshop Version**
> Engineers Workshop v1.2.0
Forge v12.18.3.2254
Woot v1.2.6

###### **Expected behavior**
> Woot uses recipes that return items upon completion of the crafting.

###### **Actual Behavior**
> Items are not returned

###### **Steps to reproduce** *[If Applicable]*
> Attempt crafting recipe that returns items.

--Additional Information--
Honestly, I haven't done as much testing or expirimenting as I normally would before I report an issue, so I'm not sure if it's an issue with Woot or with Engineers Workshop. I can however, confirm that the recipes works successfully in a Tinkers' Crafting Table.

**Comment by JorVaCoding** [comment]
I'm assuming that it's like the cake recipe (returns buckets). If this is the case it should be an easy fix. I also need to test cake recipe to see if that is working.

**Comment by JorVaCoding** [comment]
Not reproducible, I tried making the "Factory Casing" from woot and had no issue, it returned the hammer and casing die (I assume that how it's supposed to work), If you could give more detail on what you crafted that caused this issue I will reopen and fix, for now, closing this issue.
