### ISSUE TITLE
Random server crashes

### ISSUE THREAD

**Issue by Chris-FireFox** [EngineersMods/EngineersWorkshop#25]
###### **Forge Version & Engineer's Workshop Version**
> Forge Version 12.18.3.2254 Engineers Workshop 1.2.1-1.10.2

###### **Expected behavior**
> smelting or alloying x item

###### **Actual Behavior**
> crashes the server sometimes at item completion

###### **Link to Crashlog or Forgelog** *[If Applicable]*

java.lang.NullPointerException: Ticking block entity
    at engineers.workshop.common.table.TileTable.lambda$sendToAllPlayersExcept$0(TileTable.java:217)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)

###### **Steps to reproduce** *[If Applicable]*
> the error seems to be coming and going as it pleases

**Comment by EwyBoy** [comment]
We are gonna look into it, thanks!

**Comment by Chris-FireFox** [comment]
it was in an FTB beyod pack and the server have so far been crashed while smelting binder composite by furnace, alloying iron and redstone and making quite clear glass

**Comment by JaSpr** [comment]
This happens very rarely, but sometimes when we're manually removing smelted ingots from the output, the server crashes entirely.  Mind you, we process a lot of ores, but this seems to happen very randomly.

We are also running FTB Beyond.

**Comment by JaSpr** [comment]
We're running 1.3.2, by the way

**Comment by EwyBoy** [comment]
Try to update to 1.3.5, we fixed a ton of bugs since 1.3.2.
Download: https://minecraft.curseforge.com/projects/engineers-workshop/files/2419474
If it still crashes, then we know it did not get fixed and we can spend some time and resources on tracking the bug down.

**Comment by JaSpr** [comment]
I believe this is a multi-player-only bug, as it has to do with sending network packets to players.  I have had this occur both with only 1 player on the MP server, and with more than 1 player.

**Comment by JaSpr** [comment]
Also, since we're using a modpack, it's not as easy to upgrade to a specific version

**Comment by JorVaCoding** [comment]
It's shouldn't really be a "MP only bug" since single player also sends packets to the world "server".

**Comment by JorVaCoding** [comment]
I added in a bunch of null checks at this line, This might fix it. This error is weird. Looks like the time it took for the table to manage everything and send packets, it went into the next game tick and tried to use the next instance of the table? I'm closing this for now, if this bug happens again please re-open and add more data.
