### ISSUE TITLE
Rotating the workshop with a crescent hammer wipes the inventory

### ISSUE THREAD

**Issue by misterfixit** [EngineersMods/EngineersWorkshop#28]
###### **Forge Version & Engineer's Workshop Version**
> 12.18.3.2281 1.2.1-1.10.2

###### **Expected behavior**
> When rotating it should rotate and keep inventory

###### **Actual Behavior**
> When you rotate it wipes the inventory and upgrades

###### **Link to Crashlog or Forgelog** *[If Applicable]*
> not applicable

###### **Steps to reproduce** *[If Applicable]*
> right click workshop with crescent hammer

**Comment by JorVaCoding** [comment]
Reproducible with Yeta Wrench, fixing now

**Comment by JorVaCoding** [comment]
Fixed, will be a version later today along with other bug fixes. (I'll once it's committed)

**Comment by JorVaCoding** [comment]
1.3.0-1.10.2
