### ISSUE TITLE
Auto Transfer not working with furnace and crafting table

### ISSUE THREAD

**Issue by Dafri84** [EngineersMods/EngineersWorkshop#31]
###### **Forge Version & Engineer's Workshop Version [MAKE SURE YOU ARE RUNNING THE LATEST BUILD]**
> Forge 12.18.3.2281 \ Engineer's Workshop 1.3.3 - 1.10.2

###### **Expected behavior**
> Settings for auto-transfer inputs and outputs for pulling and\or depositing items in chests.

###### **Actual Behavior**
> The fuel works as intended, but crafting tables and furnaces are not receiving or depositing items in chests.

###### **Link to Crashlog or Forgelog** *[If Applicable]*
> N/A

###### **Steps to reproduce** *[If Applicable]*
> Place Workshop Table and place one chest on either side. Place furnace or crafting table in upgrade tab. Put in Auto-Transfer Upgrade. Set inputs and outputs for automation. For me this does nothing, but fuel still works receiving and depositing any fuel put in the chests. Was following the steps in the Mod Spotlight for auto-transfer.
Tried with modpack enabled and with only Engineering Workshop enabled. same results. Was experiencing this in version 1.3.2-1.10.2.

**Comment by JorVaCoding** [comment]
Fixed check the update coming out tonight
