### ISSUE TITLE
Changes made between 1.3.2 / 1.3.4 cause installed upgrades to change when switching between versions.

### ISSUE THREAD

**Issue by JaSpr** [EngineersMods/EngineersWorkshop#34]
We upgraded to 1.3.4, then all of our upgrades to our two workbenches became different upgrades.  I then had to recreate all the upgrades to be the ones which we wanted.  After finding an issue with 1.3.4 (#33) we reverted to 1.3.2 and again had invalid upgrades (they had changed to something else).  I was fortunately able to re-install the original upgrades which I had stored.

This means that, for users of the mod, upgrading will cause their setup to break.

**Comment by JorVaCoding** [comment]
I could fix this but then the upgrades would glitch again for people who load 1.3.4...
It's because I added an upgrade but it wasnt at the end of the list so it moved the other upgrades down a spot in metadata

**Comment by JorVaCoding** [comment]
Just going to have to deal with upgrades going back, hopefully not to many worlds updated to the new version and will go to the one I release soon instead...
