### ISSUE TITLE
Workshop Table not accepting input or output

### ISSUE THREAD

**Issue by hakr14** [EngineersMods/EngineersWorkshop#38]
###### **Forge Version & Engineer's Workshop Version [MAKE SURE YOU ARE RUNNING THE LATEST BUILD]**
> In the latest SkyFactory 3 update, the Workshop Table seems to have stopped working!

###### **Expected behavior**
> Crafting table upgrade accepts input from specified sides, and outputs on specified side

###### **Actual Behavior**
> Neither action occurs

###### **Steps to reproduce** *[If Applicable]*

> 1. Set up Workshop table autocrafter (workshop table, hoppers, , crafting table, auto crafter upgrade, etc.)
> 2. Specify sides for input, output, and fuel
> 3. Input a recipe

Note: Strangely, the table DOES still accept fuel from hoppers, but seems to completely ignore the crafting table's set input and output.

**Comment by JorVaCoding** [comment]
Please state the version, we did fix this bug already, but if this is new I need to know.

**Comment by hakr14** [comment]
The bug is present in version 1.3.3-1.10.2. As I'm using a modpack, it's quite possible this is somehow caused by a compatibility issue.

**Comment by JorVaCoding** [comment]
This was fixed in 1.3.4-1.10.2
