### ISSUE TITLE
Malformed JSON

### ISSUE THREAD

**Issue by LemADEC** [EngineersMods/EngineersWorkshop#40]
###### **Forge Version & Engineer's Workshop Version [MAKE SURE YOU ARE RUNNING THE LATEST BUILD]**
EngineersWorkshop-1.3.5-1.10.2.jar

###### **Expected behavior**
No exception in logs

###### **Actual Behavior**
```
[03:38:17] [Server thread/ERROR] [FML]: The mcmod.info file in EngineersWorkshop-1.3.5-1.10.2.jar cannot be parsed as valid JSON. It will be ignored
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 10
>       at com.google.gson.JsonParser.parse(JsonParser.java:65) ~[JsonParser.class:?]
>       at net.minecraftforge.fml.common.MetadataCollection.from(MetadataCollection.java:63) [MetadataCollection.class:?]
>       at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:63) [JarDiscoverer.class:?]
>       at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:49) [ContainerType.class:?]
>       at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:78) [ModCandidate.class:?]
>       at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:141) [ModDiscoverer.class:?]
>       at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:392) [Loader.class:?]
>       at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:531) [Loader.class:?]
>       at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) [FMLServerHandler.class:?]
>       at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) [FMLCommonHandler.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 10
>       at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[JsonReader.class:?]
>       at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1386) ~[JsonReader.class:?]
>       at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:531) ~[JsonReader.class:?]
>       at com.google.gson.stream.JsonReader.peek(JsonReader.java:414) ~[JsonReader.class:?]
>       at com.google.gson.JsonParser.parse(JsonParser.java:60) ~[JsonParser.class:?]
>       ... 12 more
```

###### **Link to Crashlog or Forgelog** *[If Applicable]*
n/a

###### **Steps to reproduce** *[If Applicable]*
n/a

**Comment by EmanYm** [comment]
This is the error I'm seeing on the server I'm helping with
https://hastebin.com/ceqisopuvo.css

The author should use this to make sure their json files are valid
http://www.jsoneditoronline.org/

**Comment by Keaft** [comment]
So the description for Engineers Workshop is a tad misleading, for the 1.7.10 version, which I assume is what you are using to get this same error that I did, you need the Ewy's Workshop plugin. It's the same dude. Though sadly this older version doesn't give the North-South-East-West options for picking sides. It's a tad confusing being left-right-back-front options. Luckily top and bottom are easy enough.

https://minecraft.curseforge.com/projects/ewys-workshop

Edit: Derp. I had assumed that it worked on the 1.10.2 version without error as I was able to use the Skyfactory 3 modpack which contains the Engineers Workshop mod. However, I can see this Json error as mentioned above in this modpack as well.

**Comment by LemADEC** [comment]
We're using 1.3.5-1.10.2 which is for 1.10.2, as seen here: https://minecraft.curseforge.com/projects/engineers-workshop

**Comment by EmanYm** [comment]
The error tells me it's a problem with the [mcmod.info](https://github.com/EngineersMods/EngineersWorkshop/blob/10cccbc329b489c6407c9c559b517e34309a8c50/build.gradle), not the plugin version.  [Looking at that file](https://hastebin.com/gefutuzoki.rb), I think I see why.
@JorVaCoding or @EwyBoy should look into fixing it with the json parser I posted above
