### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by Nikole22** [EngineersMods/EngineersWorkshop#47]
[crash-2018-02-18_16.33.38-server.txt](https://github.com/EngineersMods/EngineersWorkshop/files/1734802/crash-2018-02-18_16.33.38-server.txt)

**Comment by JorVaCoding** [comment]
Could you give some more information on what was going on before the crash?

**Comment by Nikole22** [comment]
Sorry, I actually don't now what happened but now all is great.

2018-02-22 3:39 GMT+02:00 JorVa <notifications@github.com>:

**Comment by JorVaCoding** [comment]
Okay, if you run into this again, please re-open this with more info.
