### ISSUE TITLE
Workbench does not use blocks of Coal as fuel source.

### ISSUE THREAD

**Issue by medtryx** [EngineersMods/EngineersWorkshop#5]
**** This is not an Issue, Power Capacity Upgrade had not been installed.****

###### **Forge Version & Engineer's Workshop Version**
forge-12.18.3.2185
EngineersWorkshop-1.0.2-1.10.2.jar

###### **Expected behavior**
> Workshop Table should use Block of Coal as a fuel source.

###### **Actual Behavior**
> Workshop Table  does not use the Block of Coal. Coal and Charcoal both work fine, as well as every other wooden item that I've tested that will work in a normal furnance. 

###### **Steps to reproduce** *[If Applicable]*
> Only installed mods for testing are JEI, MouseTweaks, and Inventory Tweaks as well as Forge and EngineersWorkshop.

**Comment by medtryx** [comment]
I was mistaken, this worked after testing again and placing Power Capacity Upgrade. I thought I had used them the first time but must not have.

**Comment by JorVaCoding** [comment]
The issue is that we don't consume fuel if we don't have enough room to store it, we make tweak the values of fuel or of the default power. But currently you will need to have capacity upgrades to allow coal blocks.
