### ISSUE TITLE
Anvil used up when creating Flat Transfer Node

### ISSUE THREAD

**Issue by WilxGaming** [EngineersMods/EngineersWorkshop#50]
###### **Forge Version & Engineer's Workshop Version 
forge-14.23.4.2705
EngineersWorkshopReborn-1.12.2-1.0.8.37

###### **Expected behavior**
When crafting a Flat transfer node in a crafting table you get back the Anvil

###### **Actual Behavior**
When crafting a Flat transfer node in a Workshop table you DON'T get back the Anvil

Video:
http://www.youtube.com/watch?v=AVz2YugZQqE&t=22m53s

**Comment by EwyBoy** [comment]
engineers workshop reborn issues can be reported to the dev here: https://github.com/TechReborn/EngineersWorkshopReborn/issues
