### ISSUE TITLE
Missing Upgrades 1.12.2

### ISSUE THREAD

**Issue by ghost** [EngineersMods/EngineersWorkshop#51]
A lot of the upgrades are missing in 1.12.2 version

**Comment by EwyBoy** [comment]
They are not "missing". They have been removed for various reasons. The port from 1.10 to 1.12 was pretty hard, and it is almost a miracle the thing we thew together works.
Modmuss50 took over the mod and is maintaining the 1.12 version. Use this instead:

https://minecraft.curseforge.com/projects/engineers-workshop-reborn
