### ISSUE TITLE
Workshop Table easily placed on side.

### ISSUE THREAD

**Issue by medtryx** [EngineersMods/EngineersWorkshop#6]
###### **Forge Version & Engineer's Workshop Version**
> forge-12.18.3.2185
> EngineersWorkshop-1.0.2-1.10.2.jar

###### **Expected behavior**
> Workshop Table will place with top facing up. 

###### **Actual Behavior**
> Standing on a block or jumping and placing the Workshop Table almost always places it on it's side.

**Comment by JorVaCoding** [comment]
Fixed, should be fixed in next build... Leaving this issue open because we still need to find out some sort of rotation mechanic.
