### ISSUE TITLE
Crash while Shift-Clicking item into Workshop Table

### ISSUE THREAD

**Issue by medtryx** [EngineersMods/EngineersWorkshop#7]
###### **Forge Version & Engineer's Workshop Version**
> forge-1.10.2-12.18.3.2185
> EngineersWorkshop-1.0.2-1.10.2.jar

###### **Expected behavior**
> Game doesn't crash... 
###### **Actual Behavior**
>Accessed GUI of Workshop Table, It has 4 furnaces installed and is buring charcoal for power.  Bottom Left Furnance was smelting partial stack of  Sand into Glass.  Placed full stack of Tinker's Construct Grout into top left and top right by dragging the stack to the slot and relasing the mouse. Attempted to Shift-Click a third stack into the bottom right slot and the game crashed. 

###### **Link to Crashlog or Forgelog** *[If Applicable]*

http://pastebin.com/hJR0EvbS

**Comment by medtryx** [comment]
Crashed a second time. I was able to enter the game and access the table without issue. Placed a stack of grout in the bottom right slot by dragging and dropping. Attempted to pick them up and move them out and the game crashed. 

http://pastebin.com/pkDVHwgB

**Comment by medtryx** [comment]
I was unable to replicate this in a different world with the same profile or in a profile with only Forge, Workshop, MouseTweaks and Inventory tweaks.

**Comment by EwyBoy** [comment]
It might have been a another mod causing the bug. I consider this issue to be resolved.
