### ISSUE TITLE
Missing name and suggestion

### ISSUE THREAD

**Issue by Serico86** [EngineersMods/EngineersWorkshop#8]
###### **Forge Version & Engineer's Workshop Version**
> Forge 12.18.3.2185, Engineer's Workshop 1.0.4

Little issue and a suggestion:
-RF upgrade doesn't have a name
-Can you add the icon of the selected side like Steve's Workshop for 1.7.10?

![2016-12-16_18 50 49](https://cloud.githubusercontent.com/assets/24575754/21272992/cd8a78b2-c3c1-11e6-9d8a-1e48899d11a7.png)

**Comment by JorVaCoding** [comment]
1) Will fix rf upgrade right now :)
2) We are in the process of adding the icons, but it's a bit difficult to port with some of the changes, but it's something that we plan on adding very soon.

**Comment by JorVaCoding** [comment]
#1 icons are on the todo... will close that issue when it's finished
